version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - NODE_VERSION=15.5.0
    volumes:
      - .:/app:cached # ホストへの反映の遅延を許容して高速化する
      - node_modules:/app/node_modules
    ports:
      - "8080:8080"
volumes:
  node_modules:
    driver: local
